### ISSUE TITLE
Bug: lost selection of section after update

### ISSUE THREAD

**Issue by stdoma** [lectureStudio/MoodleSync#14]
If a section is selected in the combo box and the update is executed, the selection is lost.
The selected section in the summary table will continue to be displayed correctly after the update.

**Comment by maxkratz** [comment]
Can reproduce this one!

Before clicking on "Aktualisieren":
![1](https://user-images.githubusercontent.com/20956405/196484624-089973c1-8704-4390-8394-85dc0f2d11c1.PNG)

After:
![2](https://user-images.githubusercontent.com/20956405/196484727-483dcaf1-648e-41df-aac7-e9bb00fe21cd.PNG)
